spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  profiles:
    active: local
  jackson:
    serialization:
        fail-on-empty-beans: false