spring:
  devtools:
    livereload:
      enabled: true
  profiles:
    active: action
  jackson:
    serialization:
        fail-on-empty-beans: false
  servlet:
    multipart:
      max-file-size: 500MB
  boot:
    admin:
      client:
        url: http://localhost:9999
management:
  endpoints:
    web:
      exposure:
        include: "*"