spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        storage_engine: innodb
  devtools:
    livereload:
      enabled: true
  datasource:
#    url: jdbc:h2:mem:testdb
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
  profiles:
    active: local
  jackson:
    serialization:
        fail-on-empty-beans: false