# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Spring Boot CI & CD with Gradle - 봄내 사진 예술연구회 사진 전시회.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      accesskey: ${{secrets.accesskey}}
      secretkey: ${{secrets.secretkey}}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: 배포를 위한 폴더생성
      run: mkdir deploy

    - name: 파일 옮기기
      run: cp ./build/libs/*.jar ./deploy/

    - name: 압축파일화
      run: zip -r -qq -j ./springboot-intro-build.zip ./deploy

      #
    - name: S3 Bucket으로 이동
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_ACCESS_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_SECRET }}
      run: |
        aws s3 cp \
        --region ap-northeast-2 \
        --acl private \
        ./springboot-intro-build.zip s3://bomnae-deploy/

    - name: AWS CodeDeploy에 배포 작업
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_ACCESS_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_SECRET }}
      run: |
        aws deploy create-deployment \
        --application-name Spring-boot-Bomnae \
        --deployment-group-name BomnaeDeployGroup \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=bomnae-deploy,bundleType=zip,key=springboot-intro-build.zip \
        --region ap-northeast-2